config/routes.rb
List::Application.routes.draw do

  devise_for :users

  resources :topics do
    resources :comments
  end
  
  match '/:year/:month/:day' => 'topics#index'

  root :to => "topics#index"
  
  match 'topics/search' => 'topics#search'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :topic_id

  validates_presence_of :topic_id
  validates_presence_of :text

  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :text, :title

  validates_presence_of :title
  validates_uniqueness_of :title

  has_many :comments

  define_index do
    indexes title
    set_property :delta => true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@topic = Topic.find(params[:topic_id])
  	@comment = @topic.comments.build(params[:comment])
  	@topic.save
    @comment.save

  	redirect_to @topic
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.topic
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  respond_to :html

  def search 
    @query = params[:query]
    @topic = Topic.new
    @topics = Topic.search @query, :page => params[:page], :per_page => 10

    render :action => 'index'
  end

  def index
    unless params[:year].nil?
      @topics = Topic.where(:year => params[:year], :month => params[:month], :day => params[:day])
                   .paginate :page => params['page'], :per_page => 10
    else
      @topics = Topic.paginate :page => params['page'], :per_page => 10
    end
    
    respond_with @topics
  end

  def show
    @topic = Topic.find(params[:id])
    respond_with @topic
  end

  def new
    @topic = Topic.new
    respond_with @topic
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(params[:topic])
    time = Time.now
    @topic.year = time.year
    @topic.month = time.month
    @topic.day = time.day
    if @topic.save
      flash[:notice] = 'Topic was successfully created.'
      respond_with @topic
    else
      render action: "new"
    end
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update_attributes(params[:topic])
      flash[:notice] = 'Topic was successfully updated.'
      respond_with @topic
    else
      render action: "edit"
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    respond_with @topic
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Discussion List</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_topics.html.erb
<script>
	function quoteIt(id) {
		var comment = $("#comment_" + String(id)).text();
		$("#comment_text").val("Quoted:" + comment + "~> ");
	};
</script>

app/views/topics/index.html.erb
<h1>Discussion List</h1>

Search a topic:
<%= form_tag :controller => 'topics', :action => 'search' do %>
	<%= text_field_tag 'query', nil, :class => 'button-search' %>
	<%= submit_tag "Go!", :disable_with => '...', :class => 'search' %>
<% end %> 
<br />

<%= link_to 'New Topic', new_topic_path %>
<br />
<br />
<hr />

<% for t in @topics do %>
  <h3><%= link_to t.title, t %></h3>
  <p>( <%= t.comments.length %> comments )</p>
  <hr />
<% end %>
<%= will_paginate @topics %>
<br />

<br />
<% if current_user %>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% end %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<% if current_user %>
	<%= render 'form' %>
<% else %>
	<%= link_to 'Sign in', '/users/sign_in' %> to create a new topic.
<% end %>

<br />
<br />

<%= link_to 'Back to the Topics', topics_path %>

app/views/topics/show.html.erb
<%= render "topics/topics" %>
<p id="notice"><%= notice %></p>

<h1><%= @topic.title %></h1>
<p>( <%= @topic.comments.length %> comments )</p>
<h3>Content:</h3>
<p>
  <%= @topic.text %>
</p>


<h3>Comments:</h3>
<hr />

<% for c in @topic.comments do %>
	
<div id="comment_<%= c.id %>">
<p><%= c.text %></p>
</div>
<%= link_to_function "Quote it", "quoteIt(#{c.id})" %>
	
	<hr />
<% end %>

<%= form_for [@topic, @topic.comments.build] do |f| %>
	<p><%= f.text_area :text, :rows => 10 %></p>
	<p><%= f.submit "Submit Comment" %></p>
<% end %>

<%= link_to 'Back to the Topics', topics_path %>